# Kind cluster configuration for keylime-agents
# Agent cluster - connects to infra cluster via host NodePorts
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: keylime-agents
nodes:
- role: control-plane
